# Generated by Django 4.0.3 on 2022-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='flat',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
