# Generated by Django 4.0.3 on 2022-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_address_address_address_area_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='auth_token',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
