# Generated by Django 4.0.3 on 2022-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_registration_auth_token_registration_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='auth_token',
            field=models.CharField(max_length=100),
        ),
    ]
