# Generated by Django 4.0.3 on 2022-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_registration_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='path_token',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
