# Generated by Django 4.0.3 on 2022-11-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('cart', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('product_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
        ),
        migrations.CreateModel(
            name='trasaction',
            fields=[
                ('trasaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BinaryField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('product_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
