# Generated by Django 4.0.3 on 2022-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_trasaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasaction',
            name='status',
            field=models.IntegerField(),
        ),
    ]
