# Generated by Django 4.0.3 on 2022-11-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_trasaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='myimage'),
        ),
    ]
