# Generated by Django 4.0.3 on 2022-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
    ]
