# Generated by Django 4.0.3 on 2022-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trasaction',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
