# Generated by Django 4.0.3 on 2022-11-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_user_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
