# Generated by Django 4.0.3 on 2022-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_trasaction_product_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_orders',
            name='razor_pay_trans_id',
            field=models.CharField(default='ss', max_length=500),
        ),
    ]
