# Generated by Django 4.0.3 on 2022-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_user_orders_razor_pay_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_orders',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
    ]
